openapi: 3.0.0
info:
  title: Membership Tier Service API
  description:  Service used to retrieve and display current membership tier .
  version: 1.0
servers:
  - url: https://dev-api.belong.gg
    description: Development Server
paths:
  /membership-tiers:
    get:
      summary: Returns all membership tiers.
      description: membership tiers are related to the membership service, used to describe types of memberships for end users.
      responses:
        '200':    # status code
          description: A JSON array of membership tiers
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: No tiers found.
  /membership-tiers/id:
    get:
      summary: Returns specific membership tier based on id.
      description: membership tiers are related to the membership service, used to describe types of memberships for end users.
      responses:
        '200':    # status code
          description: A JSON array of membership tier
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: No tiers found.
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
